# name of workflow
name: Run Arxiv Papers Daily

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron:  "0 2 * * mon-fri"  # Runs every day in 12
env:

  TOKEN: ${{ secrets.ISSUE_TOKEN }}
  GITHUB_USER_NAME: olozhika # your github id
  GITHUB_USER_EMAIL: olozhika@foxmail.com # your email address
  
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: update
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
        
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.8        

      #- name: Setup Node.js environment
      #  uses: actions/setup-node@v2.5.2

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          
      - name: Run daily arxiv 
        env:
          GITHUB: ${{ secrets.GITHUB }}
        run: TOKEN=${{ secrets.ISSUE_TOKEN }} python main.py --token=TOKEN
      
      # ============================================
      # TODO [√] 更新仓库数据
      # ============================================
      - name: Setup GIT user
        uses: fregante/setup-git-user@v2.0.1

      - name: Push done work
        run: |
          git add --all
          git commit -m "Automated deployment"
          git push --force origin main
